import { E } from "./ids";
import type { Element, Matter } from "./elements";
import type { MaterialTraits, Dynamics } from "./materials";

// Stable authored discoveries; capabilities also operate independently in the world.
type Entry = {
  id: number;
  base: number;
  pair: [number, number];
  state: Matter;
  color: string;
  description: string;
  traits: Partial<MaterialTraits>;
  lifetime?: number;
};
const row = (
  id: number,
  base: number,
  pair: [number, number],
  state: Matter,
  color: string,
  description: string,
  traits: Partial<MaterialTraits> = {},
  lifetime?: number,
): Entry => ({ id, base, pair, state, color, description, traits, lifetime });
const d = (dynamics: Dynamics): Partial<MaterialTraits> => ({ dynamics });
const melt = (at: number, to: number = E.MoltenMetal) => ({
  heatTransition: { at, to },
});
const fuel = (
  ignition: number,
  duration: number,
  explosive?: number,
): Partial<MaterialTraits> => ({
  ignition,
  fuel: duration,
  explosive,
  defaultMoisture: 0,
});
const gas = (ignition: number, blast: number): Partial<MaterialTraits> => ({
  ...fuel(ignition, 50, blast),
  dynamics: { pressureBurst: 6 },
});
const acid = (strength: number): Partial<MaterialTraits> => ({
  defaultAcidity: strength,
  defaultPollution: 20,
});
const colony = (
  food: NonNullable<Dynamics["colony"]>["food"],
  extra: Partial<Dynamics> = {},
): Partial<MaterialTraits> => ({
  ...d({ colony: { food }, ...extra }),
  defaultMoisture: 55,
});
const rows: Entry[] = [
  row(
    E.Sodium,
    E.Metal,
    [E.Salt, E.Metal],
    "powder",
    "#d9dcaa",
    "Water triggers a hot hydrogen burst. Keep it dry or build a water trap.",
    {
      ...d({
        waterReaction: { gas: E.Hydrogen, heat: 700, burst: 5, residue: E.Lye },
      }),
      ...melt(100),
    },
  ),
  row(
    E.Potassium,
    E.Metal,
    [E.Sodium, E.Fertilizer],
    "powder",
    "#c2a7e2",
    "An even larger violet water-triggered blast; nearby fuels can catch fire.",
    d({
      waterReaction: { gas: E.Hydrogen, heat: 950, burst: 8, residue: E.Ash },
      glow: true,
    }),
  ),
  row(
    E.Lithium,
    E.Metal,
    [E.Sodium, E.Stone],
    "powder",
    "#d0c7bb",
    "Slow water reactions release hydrogen and heat; useful for compact batteries.",
    d({ waterReaction: { gas: E.Hydrogen, heat: 350, residue: E.Lye } }),
  ),
  row(
    E.Calcium,
    E.Metal,
    [E.Limestone, E.Metal],
    "powder",
    "#d9d1a9",
    "Reacts with water to make alkaline lime and hydrogen.",
    d({ waterReaction: { gas: E.Hydrogen, heat: 170, residue: E.Quicklime } }),
  ),
  row(
    E.Magnesium,
    E.Metal,
    [E.Metal, E.Sulfur],
    "powder",
    "#f4ecdb",
    "Burns hot enough to ignite neighbors, with bright white embers.",
    {
      ...fuel(420, 100),
      burnProduct: E.Quicklime,
      ...d({ thermal: 950, glow: true }),
    },
  ),
  row(
    E.Aluminum,
    E.Metal,
    [E.Metal, E.Pumice],
    "powder",
    "#bfcce1",
    "Light conductive powder. Rust makes thermite; acid releases hydrogen.",
    {
      ...melt(660),
      ...d({
        contacts: [
          { target: E.Rust, product: E.Thermite, self: E.Thermite },
          { target: E.Acid, product: E.Hydrogen, self: E.Salt },
        ],
      }),
    },
  ),
  row(
    E.Zinc,
    E.Metal,
    [E.Metal, E.Chalk],
    "powder",
    "#a6bfba",
    "Acid dissolves zinc into salt and flammable hydrogen.",
    {
      ...melt(420),
      ...d({
        contacts: [{ target: E.Acid, product: E.Hydrogen, self: E.Salt }],
      }),
    },
  ),
  row(
    E.Nickel,
    E.Metal,
    [E.Metal, E.Basalt],
    "solid",
    "#acb58a",
    "A magnetic conductor that catalyzes oil into warm methane.",
    {
      ...melt(1450),
      ...d({ contacts: [{ target: E.Oil, product: E.Methane, heat: 100 }] }),
    },
  ),
  row(
    E.Tungsten,
    E.Metal,
    [E.Steel, E.Diamond],
    "solid",
    "#8fa0b1",
    "A heat-resistant electrode. Electrify it to make a compact furnace.",
    { acidResistance: 1, ...d({ powered: "heat", thermal: 1500 }) },
  ),
  row(
    E.Lead,
    E.Metal,
    [E.Metal, E.Mercury],
    "solid",
    "#6d748b",
    "Shields radiation along its blocked rays, but pollutes touching water.",
    { polluting: 1, ...melt(330), ...d({ shield: true }) },
  ),
  row(
    E.Silicon,
    E.Crystal,
    [E.Quartz, E.Metal],
    "solid",
    "#959cc1",
    "A resistive semiconductor: charged particles turn local electrical energy into heat.",
    {
      electrical: 0.45,
      ...d({ powered: "heat", thermal: 450 }),
      ...melt(1400),
    },
  ),
  row(
    E.Graphite,
    E.Coal,
    [E.Coal, E.Diamond],
    "powder",
    "#4d5964",
    "Carbon that conducts charge and burns slowly. A powder electrode.",
    { electrical: 0.85, ...fuel(600, 240), acidResistance: 0.9 },
  ),
  row(
    E.Phosphorus,
    E.Sulfur,
    [E.Fertilizer, E.Fire],
    "powder",
    "#dfff86",
    "Dry phosphorus ignites near room temperature and feeds a glowing fire.",
    {
      ...fuel(35, 100),
      ...d({ thermal: 650, glow: true }),
      burnProduct: E.Acid,
    },
  ),
  row(
    E.Nitrate,
    E.Salt,
    [E.Fertilizer, E.Oxygen],
    "powder",
    "#e4e5ba",
    "Dissolves into nutrients; contact with fuel primes an oxygen-rich explosive mix.",
    {
      soluble: "nutrients",
      defaultFertility: 90,
      ...d({
        contacts: [
          { target: E.Coal, product: E.Gunpowder, self: E.Gunpowder },
          { target: E.Sugar, product: E.RocketFuel, self: E.RocketFuel },
        ],
      }),
    },
  ),
  row(
    E.Peroxide,
    E.Water,
    [E.Water, E.Oxygen],
    "liquid",
    "#b9f5f0",
    "Silver catalyzes it into oxygen foam. Organic matter is oxidized and heated.",
    {
      ...acid(12),
      ...d({
        contacts: [
          { target: E.Silver, product: E.Silver, self: E.Oxygen, heat: 150 },
          { target: E.Plant, product: E.Foam, self: E.Oxygen, heat: 80 },
        ],
      }),
    },
  ),
  row(
    E.Bleach,
    E.Water,
    [E.Lye, E.Chlorine],
    "liquid",
    "#e2f1b0",
    "Kills spreading infection; acid releases a cloud of chlorine.",
    {
      ...acid(0),
      ...d({
        cure: true,
        contacts: [
          { target: E.Acid, product: E.Chlorine, self: E.Chlorine },
          { target: E.Vinegar, product: E.Chlorine, self: E.Chlorine },
        ],
      }),
    },
  ),
  row(
    E.Ammonia,
    E.Water,
    [E.Nitrogen, E.Water],
    "liquid",
    "#c5d6a6",
    "Nutrient-rich but toxic. Bleach turns it into choking gas.",
    {
      defaultPollution: 60,
      defaultFertility: 80,
      ...d({
        contacts: [{ target: E.Bleach, product: E.Chlorine, self: E.Chlorine }],
      }),
    },
  ),
  row(
    E.Chlorine,
    E.Smoke,
    [E.Salt, E.Oxygen],
    "gas",
    "#c0dd59",
    "Toxic gas contaminates water and burns living tissue through acidity.",
    {
      defaultPollution: 90,
      polluting: 8,
      defaultAcidity: 60,
      ...d({ pressureBurst: 5 }),
    },
    500,
  ),
  row(
    E.Methane,
    E.Hydrogen,
    [E.Coal, E.Hydrogen],
    "gas",
    "#b3c695",
    "Fast-rising gas. Ignite pockets for spreading fireballs.",
    gas(160, 8),
    550,
  ),
  row(
    E.Propane,
    E.Hydrogen,
    [E.Oil, E.Hydrogen],
    "gas",
    "#d4b189",
    "Longer-lived fuel gas makes a larger blast than methane.",
    gas(210, 10),
    900,
  ),
  row(
    E.Acetylene,
    E.Hydrogen,
    [E.Coal, E.Steam],
    "gas",
    "#eee4ab",
    "A volatile welding gas; even modest heat can launch a hot chain reaction.",
    gas(110, 11),
    400,
  ),
  row(
    E.Nitrogen,
    E.CarbonDioxide,
    [E.Steam, E.CarbonDioxide],
    "gas",
    "#9bbfe9",
    "Inert gas suppresses fire and can be condensed into a powerful coolant.",
    {
      suppressant: true,
      coldTransition: { at: -90, to: E.LiquidNitrogen },
      dynamics: { pressureBurst: 4 },
    },
    600,
  ),
  row(
    E.LiquidNitrogen,
    E.Water,
    [E.Nitrogen, E.Ice],
    "liquid",
    "#8ddcf5",
    "Flash-boils above −80°C, cooling neighbors and pressurizing tight spaces.",
    {
      aqueous: false,
      defaultTemperature: -100,
      heatTransition: { at: -80, to: E.Nitrogen },
      ...d({ thermal: -100 }),
    },
  ),
  row(
    E.Neon,
    E.Steam,
    [E.Nitrogen, E.Spark],
    "gas",
    "#ff768f",
    "Electricity turns neon into glowing plasma; enclosed gas stores pressure.",
    {
      defaultTemperature: 20,
      ...d({
        contacts: [{ target: E.Spark, product: E.Spark, self: E.Plasma }],
        glow: true,
        pressureBurst: 4,
      }),
    },
    800,
  ),
  row(
    E.Argon,
    E.CarbonDioxide,
    [E.Nitrogen, E.Stone],
    "gas",
    "#beafd7",
    "A long-lived fire shield that can build pressure in a sealed cavity.",
    { suppressant: true, ...d({ pressureBurst: 7 }) },
    1100,
  ),
  row(
    E.Ozone,
    E.Oxygen,
    [E.Oxygen, E.Spark],
    "gas",
    "#b6a5ff",
    "Oxidizes hot fuel, removes infection, and irritates polluted habitats.",
    { polluting: 3, ...d({ cure: true, pressureBurst: 5, glow: true }) },
    220,
  ),
  row(
    E.Radon,
    E.Smoke,
    [E.Uranium, E.Steam],
    "gas",
    "#d8ff74",
    "Radioactive vapor leaks through openings, leaving dangerous irradiated particles.",
    {
      defaultTemperature: 35,
      defaultPollution: 70,
      ...d({ radiation: 12, pressureBurst: 5, glow: true }),
    },
    480,
  ),
  row(
    E.Uranium,
    E.Metal,
    [E.Metal, E.Amethyst],
    "powder",
    "#91d04e",
    "Emits radiation. Water carries the contamination; lead shields the rays.",
    { defaultRadiation: 50, ...d({ radiation: 18, glow: true }) },
  ),
  row(
    E.Plutonium,
    E.Metal,
    [E.Uranium, E.Lava],
    "powder",
    "#c4d653",
    "An intense radioactive source. Nearby radioactive fuel heats toward a runaway burst.",
    {
      defaultRadiation: 90,
      ...d({ radiation: 35, thermal: 300, glow: true }),
      ...fuel(900, 100, 14),
    },
  ),
  row(
    E.Radium,
    E.Salt,
    [E.Uranium, E.Salt],
    "powder",
    "#a9ffc0",
    "Dissolves its radiation into water; contaminated pools can mutate neighboring organisms.",
    {
      defaultRadiation: 80,
      soluble: "salt",
      ...d({ radiation: 10, glow: true }),
    },
  ),
  row(
    E.Fallout,
    E.Ash,
    [E.Uranium, E.Ash],
    "powder",
    "#8e9a54",
    "Dirty radioactive dust. Rain transports its pollution and radioactive dose.",
    { defaultRadiation: 70, defaultPollution: 100, ...d({ radiation: 6 }) },
  ),
  row(
    E.LeadGlass,
    E.Glass,
    [E.Lead, E.Glass],
    "solid",
    "#708c89",
    "Transparent radiation shielding that melts at furnace temperatures.",
    { ...d({ shield: true }), ...melt(800, E.Glass) },
  ),
  row(
    E.ReactorFuel,
    E.Metal,
    [E.Uranium, E.Plutonium],
    "solid",
    "#bdff59",
    "Radiation drives self-heating. Water can cool it, but overheating causes a meltdown.",
    {
      defaultRadiation: 75,
      ...d({ radiation: 24, glow: true }),
      ...melt(950, E.Plutonium),
    },
  ),
  row(
    E.DepletedFuel,
    E.Stone,
    [E.ReactorFuel, E.Water],
    "powder",
    "#747e51",
    "Spent shielding grit: low radiation, high blast resistance, and heavy sediment.",
    { blastResistance: 1, ...d({ radiation: 2, shield: true }) },
  ),
  row(
    E.HeavyWater,
    E.Water,
    [E.Uranium, E.Water],
    "liquid",
    "#678ebd",
    "Dense reactor coolant slows radioactive heating while carrying dissolved contamination.",
    {
      conductivity: 0.8,
      ...d({
        contacts: [
          { target: E.ReactorFuel, product: E.DepletedFuel, self: E.Steam },
        ],
      }),
    },
  ),
  row(
    E.Tritium,
    E.Hydrogen,
    [E.HeavyWater, E.Spark],
    "gas",
    "#88ffd0",
    "Radioactive fuel gas: a spark produces a large flash and spreading fallout.",
    { ...gas(120, 14), ...d({ radiation: 10, pressureBurst: 9, glow: true }) },
    650,
  ),
  row(
    E.Plasma,
    E.Fire,
    [E.Spark, E.Spark],
    "energy",
    "#e8a3ff",
    "Superheated ionized gas melts terrain and sends electrical pulses into conductors.",
    {
      defaultTemperature: 1900,
      electrical: 1,
      ...d({ source: 240, thermal: 1900, glow: true }),
    },
    75,
  ),
  row(
    E.Lightning,
    E.Spark,
    [E.Spark, E.Copper],
    "energy",
    "#fff6be",
    "A branching electrical discharge arcs through nearby conductors and ignites fuel.",
    { ...d({ source: 255, powered: "arc", range: 10, glow: true }) },
    35,
  ),
  row(
    E.BallLightning,
    E.Spark,
    [E.Lightning, E.Plasma],
    "energy",
    "#cf9cff",
    "A drifting electrical storm with repeated short arcs and a finite lifetime.",
    { ...d({ source: 220, powered: "arc", range: 7, glow: true }) },
    220,
  ),
  row(
    E.Battery,
    E.Metal,
    [E.Lithium, E.Copper],
    "solid",
    "#d6b14d",
    "Finite charge source. It powers touching conductors until its vitality reserve runs out.",
    d({ source: 180 }),
  ),
  row(
    E.Capacitor,
    E.Metal,
    [E.Battery, E.Glass],
    "solid",
    "#8fbfd0",
    "Stores incoming pulses as pressure, then discharges a radial shock when fully charged.",
    d({ pressureBurst: 7 }),
  ),
  row(
    E.TeslaCoil,
    E.Metal,
    [E.Copper, E.Lightning],
    "solid",
    "#c395eb",
    "Supply charge to throw arcs across short gaps toward conductive particles.",
    d({ powered: "arc", range: 12, glow: true }),
  ),
  row(
    E.Heater,
    E.Metal,
    [E.Copper, E.Fire],
    "solid",
    "#ed9a66",
    "Converts electrical charge into local heat. Insulate it to build a furnace.",
    d({ powered: "heat", thermal: 1000 }),
  ),
  row(
    E.Cooler,
    E.Metal,
    [E.Metal, E.Snow],
    "solid",
    "#7ad6eb",
    "Powered refrigeration freezes surrounding liquids and quenches hot fuel.",
    d({ powered: "cold", thermal: -100 }),
  ),
  row(
    E.SolarCell,
    E.Glass,
    [E.Silicon, E.Glass],
    "solid",
    "#6976b5",
    "Generates charge only when open sky is directly above it; roofs cut power.",
    { electrical: 0.8, ...d({ source: 100 }) },
  ),
  row(
    E.Electrode,
    E.Metal,
    [E.Graphite, E.Copper],
    "solid",
    "#aa867b",
    "Powered electrolysis splits nearby water into hydrogen and oxygen.",
    d({ powered: "electrolysis" }),
  ),
  row(
    E.Electrolyte,
    E.Water,
    [E.Salt, E.Acid],
    "liquid",
    "#87ebbf",
    "Highly conductive acidic liquid; helps distribute charge through a liquid circuit.",
    { electrical: 1, defaultAcidity: 15, defaultPollution: 25 },
  ),
  row(
    E.Superconductor,
    E.Metal,
    [E.Metal, E.LiquidNitrogen],
    "solid",
    "#8de4e6",
    "Cold conductor passes pulses efficiently; warmth turns it back into ordinary Metal.",
    { electrical: 5, defaultTemperature: -90, ...melt(-20, E.Metal) },
  ),
  row(
    E.Magnet,
    E.Metal,
    [E.Iron, E.Spark],
    "solid",
    "#bc6d83",
    "Pulls loose conductive particles nearby. Solid walls block their motion.",
    d({ force: "magnet", range: 7 }),
  ),
  row(
    E.Electromagnet,
    E.Metal,
    [E.Magnet, E.Copper],
    "solid",
    "#cc8967",
    "A stronger magnetic field switched on by electrical charge.",
    d({ powered: "magnet", range: 11 }),
  ),
  row(
    E.Ferrofluid,
    E.Oil,
    [E.Magnet, E.Oil],
    "liquid",
    "#434a67",
    "Conductive magnetic fluid crawls toward magnets and still burns like oil.",
    { electrical: 0.7, viscosity: 2 },
  ),
  row(
    E.Repulsor,
    E.Crystal,
    [E.Magnet, E.Crystal],
    "solid",
    "#da8fed",
    "Powered repulsion pushes loose particles outward; build a particle fountain.",
    { electrical: 1, ...d({ powered: "repel", range: 9, glow: true }) },
  ),
  row(
    E.GravityWell,
    E.Obsidian,
    [E.Magnet, E.Obsidian],
    "solid",
    "#71508c",
    "Pulls nearby loose matter inward. Dense walls contain its reach.",
    d({ force: "pull", range: 10, glow: true }),
  ),
  row(
    E.WhiteHole,
    E.Crystal,
    [E.GravityWell, E.Spark],
    "solid",
    "#e7e2ff",
    "Continuously repels loose particles in a wide radius.",
    d({ force: "push", range: 10, glow: true }),
  ),
  row(
    E.Antimatter,
    E.Spark,
    [E.Plasma, E.GravityWell],
    "energy",
    "#ff84d7",
    "Contact with ordinary matter annihilates both into a hot blast. Empty space is safe.",
    { defaultTemperature: 20, ...d({ annihilate: true, glow: true }) },
    180,
  ),
  row(
    E.DarkMatter,
    E.Obsidian,
    [E.GravityWell, E.Coal],
    "powder",
    "#48365f",
    "Falling gravity grains attract loose matter while resisting ordinary explosions.",
    d({ force: "pull", range: 4 }),
  ),
  row(
    E.VoidDust,
    E.Sand,
    [E.Antimatter, E.Ash],
    "powder",
    "#84619c",
    "Consumes adjacent unshielded matter, spending its finite reserve as it eats.",
    d({ force: "void", range: 3, glow: true }),
  ),
  row(
    E.Neutronium,
    E.Obsidian,
    [E.GravityWell, E.Metal],
    "solid",
    "#8391b3",
    "An immovable containment wall. Blocks radiation and survives ordinary blasts.",
    { conductivity: 0.02, ...d({ shield: true }) },
  ),
  row(
    E.Aerogel,
    E.Glass,
    [E.Sponge, E.Glass],
    "solid",
    "#bde5ea",
    "Light insulating scaffold with enormous absorbency; soaking changes its thermal behavior.",
    {
      conductivity: 0.005,
      absorbency: 100,
      blastResistance: 0,
      ...melt(900, E.Glass),
    },
  ),
  row(
    E.Thermite,
    E.Gunpowder,
    [E.Aluminum, E.Rust],
    "powder",
    "#cc7753",
    "Ignites into an intense metal-melting shower instead of a conventional explosion.",
    {
      ...fuel(260, 180),
      explosive: undefined,
      burnProduct: E.MoltenMetal,
      ...d({ thermal: 1900, glow: true }),
    },
  ),
  row(
    E.Napalm,
    E.Oil,
    [E.Oil, E.Rubber],
    "liquid",
    "#cb7748",
    "Slow sticky fuel burns for a long time and throws burning embers.",
    {
      viscosity: 10,
      ...fuel(150, 350),
      ...d({ emit: { id: E.Ember, chance: 0.5, cost: 5 }, thermal: 850 }),
    },
  ),
  row(
    E.Nitro,
    E.Oil,
    [E.Alcohol, E.Nitrate],
    "liquid",
    "#eec371",
    "Volatile liquid: heat or an electrical pulse starts a wide explosion.",
    { ...fuel(90, 40, 15), ...d({ pressureBurst: 15 }) },
  ),
  row(
    E.Dynamite,
    E.Gunpowder,
    [E.Nitro, E.Sawdust],
    "solid",
    "#d5685d",
    "Stable placeable charge. Fire initiates a terrain-breaking blast.",
    fuel(160, 40, 17),
  ),
  row(
    E.Firework,
    E.Gunpowder,
    [E.Gunpowder, E.Magnesium],
    "powder",
    "#ed89b4",
    "Ignition launches glowing sparks upward, then bursts into colored plasma.",
    {
      ...fuel(100, 65),
      burnProduct: E.Plasma,
      ...d({
        emit: { id: E.Spark, chance: 0.8, cost: 3 },
        thermal: 700,
        glow: true,
      }),
    },
  ),
  row(
    E.FlashPowder,
    E.Gunpowder,
    [E.Aluminum, E.Nitrate],
    "powder",
    "#f3e4b4",
    "A small hot flash with a low ignition threshold; effective as a chain-reaction fuse.",
    fuel(65, 20, 6),
  ),
  row(
    E.RocketFuel,
    E.Oil,
    [E.Nitrate, E.Sugar],
    "liquid",
    "#eea085",
    "Burning propellant jets hot gas and pressure out of its open edges.",
    {
      ...fuel(130, 180),
      ...d({
        emit: { id: E.Plasma, chance: 0.6, cost: 4 },
        pressureBurst: 9,
        thermal: 1200,
      }),
    },
  ),
  row(
    E.Ember,
    E.Coal,
    [E.Coal, E.Lava],
    "powder",
    "#ff8c4b",
    "Falling hot coals spread fire; they cool into charcoal when their glow expires.",
    {
      defaultTemperature: 700,
      expiresTo: E.Charcoal,
      ...d({ thermal: 700, glow: true }),
    },
    140,
  ),
  row(
    E.Cinder,
    E.Pumice,
    [E.Pumice, E.Fire],
    "powder",
    "#ac6352",
    "Porous hot ash hisses into steam on contact with water.",
    {
      defaultTemperature: 450,
      ...d({ waterReaction: { gas: E.Steam, heat: 180, residue: E.Pumice } }),
    },
  ),
  row(
    E.SulfuricAcid,
    E.Acid,
    [E.Sulfur, E.Water],
    "liquid",
    "#d0d86a",
    "Concentrated acid chars organic matter and corrodes vulnerable metals.",
    {
      ...acid(100),
      ...d({
        contacts: [
          { target: E.Wood, product: E.Charcoal, heat: 220 },
          { target: E.Sugar, product: E.Charcoal, heat: 300 },
        ],
      }),
    },
  ),
  row(
    E.HydrochloricAcid,
    E.Acid,
    [E.Chlorine, E.Water],
    "liquid",
    "#a4e889",
    "Strong acid releases hydrogen from zinc and reactive metals.",
    {
      ...acid(85),
      ...d({
        contacts: [
          { target: E.Zinc, product: E.Hydrogen, self: E.Salt },
          { target: E.Aluminum, product: E.Hydrogen, self: E.Salt },
        ],
      }),
    },
  ),
  row(
    E.NitricAcid,
    E.Acid,
    [E.Nitrate, E.Acid],
    "liquid",
    "#dbe47e",
    "Oxidizing acid primes cotton into explosive propellant.",
    {
      ...acid(95),
      ...d({
        contacts: [{ target: E.Cotton, product: E.RocketFuel, self: E.Water }],
      }),
    },
  ),
  row(
    E.AquaRegia,
    E.Acid,
    [E.NitricAcid, E.HydrochloricAcid],
    "liquid",
    "#f1c85c",
    "Dissolves even gold into contaminated liquid, consuming the acid in the process.",
    {
      ...acid(100),
      ...d({
        contacts: [
          { target: E.Gold, product: E.Electrolyte, self: E.Water },
          { target: E.Silver, product: E.Electrolyte, self: E.Water },
        ],
      }),
    },
  ),
  row(
    E.Vinegar,
    E.Water,
    [E.Alcohol, E.Oxygen],
    "liquid",
    "#d8c995",
    "Weak acid makes baking soda fizz into pressurized carbon dioxide.",
    {
      ...acid(25),
      ...d({
        contacts: [
          {
            target: E.BakingSoda,
            product: E.CarbonDioxide,
            self: E.Foam,
            burst: 3,
          },
        ],
      }),
    },
  ),
  row(
    E.BakingSoda,
    E.Salt,
    [E.Salt, E.CarbonDioxide],
    "powder",
    "#eee8d1",
    "Buffers acid and foams when acidic particles touch it.",
    {
      soluble: null,
      neutralizer: true,
      defaultFertility: 65,
      ...d({
        contacts: [
          { target: E.Acid, product: E.Foam, self: E.CarbonDioxide, burst: 3 },
        ],
      }),
    },
  ),
  row(
    E.Quicklime,
    E.Chalk,
    [E.Limestone, E.Fire],
    "powder",
    "#e8dab9",
    "Hydration releases heat; mix with clay to discover cement.",
    { ...d({ waterReaction: { gas: E.Steam, heat: 250, residue: E.Chalk } }) },
  ),
  row(
    E.Cement,
    E.Clay,
    [E.Quicklime, E.Clay],
    "powder",
    "#a9a89b",
    "Water hardens loose cement into a solid concrete barrier.",
    {
      ...d({ waterReaction: { gas: E.Water, heat: 35, residue: E.Concrete } }),
    },
  ),
  row(
    E.Concrete,
    E.Stone,
    [E.Cement, E.Water],
    "solid",
    "#8b9390",
    "A strong barrier that insulates machinery and erodes slowly in acid.",
    {
      conductivity: 0.05,
      blastResistance: 0.85,
      acidResistance: 0.7,
      ...melt(1200, E.Lava),
    },
  ),
  row(
    E.HydrogenSulfide,
    E.Hydrogen,
    [E.Sulfur, E.Hydrogen],
    "gas",
    "#a7ba6b",
    "Toxic flammable gas both contaminates water and ignites in pockets.",
    { ...gas(180, 7), polluting: 7, defaultPollution: 90 },
    500,
  ),
  row(
    E.Biogas,
    E.Methane,
    [E.Compost, E.Water],
    "gas",
    "#a1b87e",
    "Dirty fuel gas from decay. Burns easily and pollutes pools before escaping.",
    { ...gas(130, 6), polluting: 2 },
    400,
  ),
  row(
    E.Yeast,
    E.Fungus,
    [E.Fungus, E.Sugar],
    "powder",
    "#ddc79d",
    "Ferments sugar into alcohol and releases carbon dioxide bubbles.",
    d({
      contacts: [{ target: E.Sugar, product: E.Alcohol, heat: 30 }],
      emit: { id: E.CarbonDioxide, chance: 0.2, cost: 8 },
    }),
  ),
  row(
    E.Bread,
    E.Wood,
    [E.Flour, E.Fire],
    "solid",
    "#c59858",
    "Porous edible-looking fuel. Moisture encourages mold to colonize it.",
    {
      defaultFertility: 60,
      absorbency: 85,
      ...fuel(180, 60),
      ...d({ contacts: [{ target: E.Mold, product: E.Mold, self: E.Mold }] }),
    },
  ),
  row(
    E.Flour,
    E.Sawdust,
    [E.Seed, E.Stone],
    "powder",
    "#e8d6b0",
    "Fine combustible dust; heat bakes damp flour into bread, dry dust flashes.",
    {
      ...fuel(190, 30, 4),
      heatTransition: { at: 150, to: E.Bread, minMoisture: 20 },
    },
  ),
  row(
    E.Starch,
    E.Sugar,
    [E.Plant, E.Flour],
    "powder",
    "#d6dec0",
    "Dissolves into nutrients. Heat and moisture turn it into a sticky gel.",
    { ...d({ waterReaction: { gas: E.Water, heat: 20, residue: E.Slime } }) },
  ),
  row(
    E.Milk,
    E.Water,
    [E.Water, E.Flour],
    "liquid",
    "#eee5ce",
    "Nutrient-rich liquid curdles into cheese beside acid or vinegar.",
    {
      defaultFertility: 65,
      ...d({
        contacts: [
          { target: E.Vinegar, product: E.Water, self: E.Cheese },
          { target: E.Acid, product: E.Water, self: E.Cheese },
        ],
      }),
    },
  ),
  row(
    E.Cheese,
    E.Wax,
    [E.Milk, E.Vinegar],
    "solid",
    "#e6c164",
    "Organic nutrient store that melts, burns, and feeds spreading mold.",
    {
      organic: true,
      defaultFertility: 75,
      heatTransition: { at: 70, to: E.Milk },
      ...d({ contacts: [{ target: E.Mold, product: E.Mold, self: E.Mold }] }),
    },
  ),
  row(
    E.Blood,
    E.Water,
    [E.Milk, E.Iron],
    "liquid",
    "#b95359",
    "Nutrient-rich conductive liquid; infection spreads through it and heat coagulates it.",
    {
      defaultFertility: 80,
      defaultPollution: 25,
      organic: true,
      electrical: 0.6,
      ...melt(80, E.Compost),
    },
  ),
  row(
    E.Bone,
    E.Limestone,
    [E.Calcium, E.Plant],
    "solid",
    "#ded4b9",
    "Mineral scaffold that buffers acid and releases fertilizer under heat.",
    { defaultFertility: 85, ...melt(600, E.Fertilizer) },
  ),
  row(
    E.Coral,
    E.Plant,
    [E.Kelp, E.Limestone],
    "solid",
    "#e88a91",
    "Builds a branching reef by consuming saline nutrient-rich water.",
    {
      ...colony("water"),
      dynamics: { colony: { food: "water", minSalt: 12, maxSalt: 70 } },
      saltTolerance: 70,
    },
  ),
  row(
    E.Spore,
    E.Pollen,
    [E.Fungus, E.Steam],
    "gas",
    "#b5c190",
    "Drifting spores land on damp soil and start a mycelium colony.",
    {
      ...d({
        contacts: [
          { target: E.Soil, product: E.Mycelium, self: E.Mycelium },
          { target: E.Compost, product: E.Mycelium, self: E.Mycelium },
        ],
      }),
    },
    700,
  ),
  row(
    E.Mycelium,
    E.Plant,
    [E.Spore, E.Soil],
    "solid",
    "#c7bdb5",
    "Spreads through fertile soil, spending nutrients to send spores into the air.",
    { ...colony("soil", { emit: { id: E.Spore, chance: 0.2, cost: 10 } }) },
  ),
  row(
    E.Mold,
    E.Plant,
    [E.Fungus, E.Bread],
    "solid",
    "#94ac68",
    "Consumes organic neighbors, converting their matter into a branching colony.",
    colony("organic"),
  ),
  row(
    E.Lichen,
    E.Plant,
    [E.Moss, E.Stone],
    "solid",
    "#b4bd68",
    "Slow soil-fed crust that filters adjacent polluted water with finite capacity.",
    { ...colony("soil"), filter: true },
  ),
  row(
    E.Vine,
    E.Plant,
    [E.Plant, E.Clay],
    "solid",
    "#4dba69",
    "Climbs and spreads through nearby fertile soil; water and compost support more growth.",
    colony("soil"),
  ),
  row(
    E.Bamboo,
    E.Wood,
    [E.Vine, E.Seed],
    "solid",
    "#adc15c",
    "Woody growth draws nutrients from wet soil, creating a burnable scaffold.",
    { ...colony("soil"), absorbency: 85 },
  ),
  row(
    E.Cactus,
    E.Plant,
    [E.Plant, E.Obsidian],
    "solid",
    "#76ad7a",
    "Stores water in absorbent tissue and uses sparse soil nutrients to branch.",
    { ...colony("soil"), absorbency: 100, defaultMoisture: 95 },
  ),
  row(
    E.Lotus,
    E.Plant,
    [E.Plant, E.Honey],
    "solid",
    "#e7aac8",
    "Freshwater growth consumes dissolved nutrients and releases drifting pollen.",
    {
      ...d({
        colony: { food: "water", maxSalt: 8 },
        emit: { id: E.Pollen, chance: 0.15, cost: 10 },
      }),
      defaultMoisture: 80,
    },
  ),
  row(
    E.Carnivore,
    E.Plant,
    [E.Vine, E.Acid],
    "solid",
    "#c86681",
    "Consumes nearby organic particles and harms creatures that touch its growth.",
    colony("organic"),
  ),
  row(
    E.GlowMoss,
    E.Moss,
    [E.Moss, E.Neon],
    "solid",
    "#84efb5",
    "A glowing soil-fed colony that supplies tiny electrical pulses while nourished.",
    { ...colony("soil", { source: 65, glow: true }), electrical: 0.4 },
  ),
  row(
    E.FireBloom,
    E.Plant,
    [E.Plant, E.Phosphorus],
    "solid",
    "#ff8b59",
    "A combustible bloom that spends nutrients throwing embers from its edges.",
    {
      ...colony("soil", {
        emit: { id: E.Ember, chance: 0.5, cost: 10 },
        glow: true,
      }),
      ignition: 650,
    },
  ),
  row(
    E.FrostBloom,
    E.Plant,
    [E.Plant, E.LiquidNitrogen],
    "solid",
    "#8ce8e5",
    "A cold bloom spreads through freshwater and slowly chills its surroundings.",
    {
      ...d({ colony: { food: "water", maxSalt: 9 }, thermal: -45, glow: true }),
      defaultTemperature: -20,
    },
  ),
  row(
    E.Mutagen,
    E.Slime,
    [E.Uranium, E.Slime],
    "liquid",
    "#b5f75b",
    "Radiation-rich slime changes organic neighbors into strange blooms or carnivores.",
    { defaultRadiation: 70, ...d({ mutate: true, radiation: 5, glow: true }) },
  ),
  row(
    E.Virus,
    E.Slime,
    [E.Mutagen, E.Blood],
    "liquid",
    "#d7759c",
    "Consumes organic matter to replicate. Heat, bleach, and antidote can stop it.",
    {
      organic: true,
      ...d({ colony: { food: "organic" } }),
      heatTransition: { at: 75, to: E.Compost },
    },
  ),
  row(
    E.Antidote,
    E.Water,
    [E.Peroxide, E.Charcoal],
    "liquid",
    "#77ddd1",
    "Consumes its reserve to cure infection, neutralize radiation, and clean touching water.",
    { filter: true, ...d({ cure: true }) },
  ),
  row(
    E.Nanite,
    E.Metal,
    [E.Silicon, E.Spark],
    "powder",
    "#a3b8e7",
    "Powered nanites convert neighboring metal into more nanites, splitting their reserve.",
    { ...d({ colony: { food: "metal", charged: true }, glow: true }) },
  ),
  row(
    E.CleanerNanite,
    E.Metal,
    [E.Nanite, E.Antidote],
    "powder",
    "#8df0d0",
    "Consumes pollution to reproduce and gradually repairs contaminated water.",
    colony("pollution", { cure: true }),
  ),
  row(
    E.Replicator,
    E.Metal,
    [E.Nanite, E.Crystal],
    "solid",
    "#c598e5",
    "Powered machine copies a touching material into adjacent air using a finite reserve.",
    d({ powered: "electrolysis", glow: true }),
  ),
  row(
    E.LivingMetal,
    E.Metal,
    [E.Nanite, E.Plant],
    "solid",
    "#8bba99",
    "Conductive colony spreads by consuming other metals when powered.",
    d({ colony: { food: "metal", charged: true } }),
  ),
  row(
    E.RustEater,
    E.Plant,
    [E.Fungus, E.Rust],
    "powder",
    "#d5a36e",
    "Feeds on rust to build an organic colony, slowly clearing corroded structures.",
    colony("rust"),
  ),
  row(
    E.CrystalSeed,
    E.Crystal,
    [E.Crystal, E.Seed],
    "powder",
    "#b895ed",
    "Seeds crystallization: converts neighboring fertile water into solid crystal branches.",
    d({ colony: { food: "water", product: E.Geode }, glow: true }),
  ),
  row(
    E.Geode,
    E.Crystal,
    [E.CrystalSeed, E.Stone],
    "solid",
    "#9873c8",
    "A mineral shell. Electrical pulses crack it into quartz and amethyst grains.",
    d({ contacts: [{ target: E.Spark, product: E.Quartz, self: E.Amethyst }] }),
  ),
  row(
    E.SaltCrystal,
    E.Crystal,
    [E.Salt, E.Crystal],
    "solid",
    "#e7c6e9",
    "Extracts salt from water to grow a solid crust, leaving fresher water behind.",
    d({ colony: { food: "water", minSalt: 20 }, glow: true }),
  ),
  row(
    E.IceNine,
    E.Ice,
    [E.Ice, E.CrystalSeed],
    "solid",
    "#98cafa",
    "A contagious fantasy ice that freezes touching water. Strong heat melts it back.",
    {
      ...d({
        contacts: [{ target: E.Water, product: E.IceNine }],
        thermal: -60,
        glow: true,
      }),
      heatTransition: { at: 65, to: E.Water },
    },
  ),
  row(
    E.LavaSponge,
    E.Sponge,
    [E.Sponge, E.Obsidian],
    "solid",
    "#d89666",
    "Swallows touching lava into obsidian while releasing a steam jet.",
    {
      ignition: 2000,
      blastResistance: 1,
      ...d({
        contacts: [{ target: E.Lava, product: E.Obsidian, heat: 300 }],
        emit: { id: E.Steam, chance: 0.3, cost: 10 },
      }),
    },
  ),
  row(
    E.Cloud,
    E.Steam,
    [E.Steam, E.Steam],
    "gas",
    "#d1e0e8",
    "A finite drifting water reservoir rains from its open edges.",
    {
      defaultTemperature: 35,
      ...d({ emit: { id: E.Water, chance: 0.4, cost: 8 }, pressureBurst: 5 }),
    },
    700,
  ),
  row(
    E.StormCloud,
    E.Steam,
    [E.Cloud, E.Spark],
    "gas",
    "#939dc5",
    "Rains while building electrical arcs: a movable storm for flooding and ignition.",
    {
      defaultTemperature: 35,
      electrical: 0.8,
      ...d({
        source: 180,
        powered: "arc",
        range: 9,
        emit: { id: E.Water, chance: 0.3, cost: 8 },
        glow: true,
      }),
    },
    650,
  ),
  row(
    E.AcidCloud,
    E.Steam,
    [E.Cloud, E.Acid],
    "gas",
    "#c1d47d",
    "Rains acid into the world, corroding metal and poisoning habitats below.",
    {
      defaultTemperature: 35,
      ...d({ emit: { id: E.Acid, chance: 0.4, cost: 8 }, pressureBurst: 6 }),
    },
    650,
  ),
];

const names = new Map<number, string>(
  Object.entries(E).map(([name, id]) => [
    id,
    name.replace(/([a-z])([A-Z])/g, "$1 $2"),
  ]),
);
export const frontierElements: Element[] = rows.map((r) => ({
  id: r.id,
  name: names.get(r.id)!,
  color: r.color,
  state: r.state,
  density:
    r.state === "gas" || r.state === "energy"
      ? 0
      : r.state === "liquid"
        ? 3
        : r.state === "solid"
          ? 9
          : 5,
  category:
    r.state === "gas"
      ? "Gases"
      : r.state === "liquid"
        ? "Liquids"
        : r.state === "energy" || r.traits.explosive
          ? "Energy"
          : r.base === E.Plant || r.base === E.Wood
            ? "Nature"
            : "Solids",
  icon:
    r.state === "gas"
      ? "steam"
      : r.state === "liquid"
        ? "water"
        : r.state === "energy"
          ? "spark"
          : r.base === E.Plant
            ? "plant"
            : r.base === E.Crystal
              ? "crystal"
              : r.state === "powder"
                ? "sand"
                : "metal",
  description: r.description,
  lifetime: r.lifetime,
}));
export const frontierTraits = rows.map((r) => ({
  id: r.id,
  base: r.base,
  traits: r.traits,
}));
export const frontierRecipes = rows.map((r) => ({
  a: r.pair[0],
  b: r.pair[1],
  products: [r.id],
  note: r.description,
}));
