import { icon } from "./icons";

export const ui = `
<header class="app-header"><a class="brand" href="./">particle<span class="brand-dot"></span></a><span id="world-name">Garden</span><div class="header-actions"><button id="journal-tab">${icon("book-open")}<span>Discoveries</span><small class="nav-count"></small></button><details id="world-menu"><summary>World ${icon("chevron-down")}</summary><div class="menu"><button id="new-world">New world</button><button id="ecology-lab">Living lab</button><button id="save">Save world</button><button id="load">Load saved world</button><button id="reset">Reset terrain</button><button id="clear">Clear world</button><hr><button id="field-guide">Field guide</button><button id="help">Controls & help</button><button id="sound">${icon("volume-x")} Discovery sound</button></div></details></div></header>
<div class="workspace">
<aside class="library" aria-label="Element palette">
  <div class="palette-heading"><strong>Palette</strong><span id="unlocked-count" title="Available materials and life"></span></div>
  <label class="search">${icon("search")}<input id="element-search" placeholder="Search elements" aria-label="Search elements" autocomplete="off"><kbd>/</kbd></label>
  <div class="categories" role="group" aria-label="Element categories">${["All", "Nature", "Life", "Liquids", "Solids", "Energy", "Gases"].map((c, i) => `<button class="category ${i === 0 ? "active" : ""}" data-category="${c}" aria-pressed="${i === 0}">${c}</button>`).join("")}</div>
  <div class="elements-scroll"><div id="element-grid" class="element-grid"></div><p id="empty-search" hidden>No matching elements.</p></div>
  <div class="selected-element" id="selected-detail"></div>
  <section class="combiner" aria-label="Combiner"><div class="combiner-heading"><strong>Combine</strong><button id="clear-lab" class="icon-button" aria-label="Clear combiner" title="Clear combiner">${icon("x")}</button></div><div id="lab-drop" class="lab-drop" tabindex="0" role="group" aria-label="Drop two elements here to combine. Press C on a palette item to add it."><div class="lab-equation"><div class="lab-slot" data-slot="0">Drop element</div><span>+</span><div class="lab-slot" data-slot="1">Drop element</div></div><div id="lab-result"></div></div><p id="lab-message" role="status" aria-live="polite">Drop two elements. See what happens.</p></section>
</aside>
<main class="world-shell">
  <div class="world-toolbar"><div class="tool-group" role="group" aria-label="Drawing tools"><button data-tool="paint" class="tool active" aria-label="Brush" title="Brush (B)">${icon("paintbrush")}</button><button data-tool="erase" class="tool" aria-label="Erase" title="Erase (E)">${icon("eraser")}</button><button data-tool="inspect" class="tool" aria-label="Inspect conditions" title="Inspect (I)">${icon("pipette")}</button><button id="undo" class="tool" aria-label="Undo last edit" title="Undo (Ctrl+Z)">${icon("undo-2")}</button></div><span class="divider"></span><div class="brush-controls"><label for="brush-size">Size</label><input id="brush-size" type="range" min="1" max="20" value="5"><output id="brush-value">5</output><button id="brush-shape" class="tool" aria-label="Switch brush shape" title="Switch brush shape">${icon("circle")}</button></div><div class="view-controls"><select id="overlay" aria-label="World overlay"><option value="natural">Natural</option><option value="temperature">Temperature</option><option value="salinity">Salinity</option><option value="moisture">Moisture</option><option value="pollution">Pollution</option><option value="fertility">Fertility</option><option value="charge">Electricity</option><option value="pressure">Pressure</option><option value="radiation">Radiation</option></select><button id="grid-toggle" class="tool" title="Toggle grid" aria-label="Toggle grid" aria-pressed="false">${icon("square")}</button><button id="fullscreen" class="tool" aria-label="Expand world" title="Expand world">${icon("maximize")}</button></div></div>
  <div class="viewport"><div class="world-stage"><div id="world"></div><div id="paused-overlay" hidden>Paused</div><span id="overlay-legend" class="overlay-legend" hidden></span><div id="inspection-panel" class="inspection-panel" hidden aria-live="polite"></div><div class="drop-cue">Release to place</div></div></div>
  <div class="statusbar"><div class="playback"><button id="pause" class="tool" aria-label="Pause simulation" title="Pause (Space)">${icon("pause")}</button><button id="step" class="tool" aria-label="Advance one frame" title="Advance one frame">${icon("step-forward")}</button><button id="speed" title="Change simulation speed">1×</button><span id="live-label">Running</span></div><button id="population" title="Inspect population">Life</button><span class="performance"><span id="particle-count">0</span> particles <span class="stat-separator">·</span> <span id="fps">60</span> fps</span></div>
  <div class="contextbar"><span id="interaction-hint">Click an element to paint. Drag one to place a blob.</span><span id="environment-event"></span></div>
</main></div>
<div class="toast" id="toast" role="status" aria-live="polite"></div><dialog id="modal"><button class="modal-close icon-button" aria-label="Close dialog">${icon("x")}</button><div id="modal-content"></div></dialog>`;
